#!/bin/sh

# PROVIDE: EquiTrader
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# EquiTrader_enable (bool): Set to NO by default. Set this variable to YES if you want to enable EquiTrader service.
# EquiTrader_config (path): Set to /usr/local/etc/EquiTrader.conf by default.
# EquiTrader_user:  The user account EquiTrader daemon runs as. It uses 'root' user by default.
# EquiTrader_group: The group account EquiTrader daemon runs as. It uses 'wheel' group by default.
# EquiTrader_datadir (str): Default to "/var/db/EquiTrader". Base data directory.

. /etc/rc.subr

name=EquiTrader
rcvar=EquiTrader_enable

: ${EquiTrader_enable:=NO}
: ${EquiTrader_config=/usr/local/etc/EquiTrader.conf}
: ${EquiTrader_datadir=/var/db/EquiTrader}
: ${EquiTrader_user="root"}
: ${EquiTrader_group="wheel"}

required_files=${EquiTrader_config}
command=/usr/local/bin/EquiTraderd
EquiTrader_chdir=${EquiTrader_datadir}
pidfile="${EquiTrader_datadir}/EquiTraderd.pid"
stop_cmd=EquiTrader_stop
command_args="-conf=${EquiTrader_config} -datadir=${EquiTrader_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

EquiTrader_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${EquiTrader_datadir}
	[ $? -eq 0 ] && chown -R ${EquiTrader_user}:${EquiTrader_group} ${EquiTrader_datadir}
}

EquiTrader_prestart()
{
	if [ ! -d "${EquiTrader_datadir}/." ]; then
		EquiTrader_create_datadir || return 1
	fi
}

EquiTrader_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

EquiTrader_stop()
{
    EquiTrader_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${EquiTrader_config} -datadir=${EquiTrader_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
